import java.util.*;

public class B05 
{
	public static void GuessingGame()
	{
		//	---------- START OF DECLARATION OF VARIABLES & CLASSES ------------	//
		//	The boolean would be used to control the do-while loop later
		boolean Solved = false;
		//	This variables would be used to keep the random numbers and the user's numbers created in two temp variables
		int randomUser, randomCPU;
		// Scanner class created to read in console input
		Scanner input = new Scanner(System.in);
		// Random class created
		Random random = new Random();		
		//	Random numbers which are created until 1000 are assigned to the temp variable
		randomCPU = random.nextInt(1000);
		
		//		---------- END OF DECLARATION OF VARIABLES ------------	//
		
		
		System.out.println("Guess my number! It's between 1 and 1000");
		
		//	This loop would be executed at least one time and depending on the boolean variable, 'Solved' 
		do
		{
			System.out.print("Your guess : ");
			//	Asks for the user's guessed integer
			randomUser = input.nextInt();
			
			//	If the number entered by the user is bigger than number generated by the CPU,
			//	make the boolean true to go through the loop for another time
			if (randomUser < randomCPU)
			{
				System.out.println("Too low!");
				Solved = true;
			}
			
			//	If the number entered by the user is smaller than number generated by the CPU,
			//	make the boolean true to go through the loop for another time
			else if (randomUser > randomCPU)
			{
				System.out.println("Too high!");
				Solved = true;
			}
			
			//	If the number entered by the user is equals to the number generated by the CPU,
			//	make the boolean false to end the loop
			else if (randomUser == randomCPU)
			{
				System.out.println("You got it!");
				Solved = false;
			}
			
		}while(Solved);
	}
}